### ISSUE TITLE
機材貸出延長時の機材番号入力ミスの場合の処理

### ISSUE THREAD

**Issue by Osamu-Sano** [soudai-aisw/aisw_bihin#37]
機材番号を入力ミスし、本来の延長対象とした機材番号でない番号が入力された場合に
そのままスルーされてしまうのを防ぐ必要がある。
下例のように、対象と売る機材名などを表示して再確認させるべき。

例：
[機材名] を延長処理します。　よろしいですか？　(Y/N)

**Comment by shinichi-ozaki** [comment]
StandbyUpdateEquipmentIdInputでID入力
↓
新規Stateで「[機材名] を延長処理します。　よろしいですか？　(Y/N)」を表示し確認する
↓
StandbyExpirationDateInputWhenUpdateで予定日入力

こんなイメージであってますか？

**Comment by shinichi-ozaki** [comment]
機材名の表示の機能って必要かな？
機材を識別できるデータは「施設ID(機材ID)」と「タグID」。
「タグID」はRFIDから読み取るデータでユーザには非公開。
よって、ユーザは「施設ID(機材ID)」を入力する。
今のDBに「施設ID(機材ID)」以上に機材名が識別できるデータがない。
「施設ID(機材ID)」表示しても防げるのはタイプミスくらいでは？

**Comment by shinichi-ozaki** [comment]
現状のDBにはDummyとして施設IDに調子こいた名称が入ってるので、
下記条件を踏まえた施設IDの命名規則を定義する必要があると考えますがどーでしょう。
・英数字
・わかりやすく、入力しやすい
・不正な入力を検出しやすい

**Comment by shiftdownet** [comment]
以下で対応済

https://github.com/soudai-aisw/aisw_bihin/commit/60ca706a0de4b5e7c876e0d2a88c540ea11b481f
