### ISSUE TITLE
カードIDと社員番号の紐付について

### ISSUE THREAD

**Issue by Osamu-Sano** [soudai-aisw/aisw_bihin#38]
カードID・社員番号の紐付は事前にDBを用意してDB外の入力ができないようにする。
未登録のカードIDの場合には登録する処理を追加する必要あり。

**Comment by shiftdownet** [comment]
下記コミットで実装。
https://github.com/soudai-aisw/aisw_bihin/commit/d7c54949a32097475e617d0711fb6f1bb9e28913
