### ISSUE TITLE
DB問い合わせ時にクエリインジェクションできる

### ISSUE THREAD

**Issue by shiftdownet** [soudai-aisw/aisw_bihin#44]
# 再現環境
Windows 10
コミットID：https://github.com/soudai-aisw/aisw_bihin/commit/c5cb42c8643deeb1f119fd541b7c7b357a2210c2

# 前提条件
現在状態が、StandbyUserIdInput
※恐らく備品番号入力時も可能

# 入力値
[1,2,3,4,.......,114514,114515,114516]

# 結果
リスト内の114514にヒットして認証される。

![image](https://user-images.githubusercontent.com/46210365/130275496-33e96a9e-8601-4cde-92a4-bf92cb962803.png)

# 対策案
社員番号はそもそもキーボード入力受け付けないようにすれば心配なくなりますが、
備品番号は手打ちするユースケースがあるので、入力形式を先にチェックしたほうがいいですね。

現状、キーボードから全角入力できないからいいですが、
カラム名が半角英数のものがあれば、自由自在にクエリが作れてしまいます。。

**Comment by A-Yasue** [comment]
INPUT処理時に、手打ちで入力される情報（社員番号、日付）は以下条件で妥当性確認する予定です。
※するのはStandbyUserIdInput作ってる人だが
・社員番号は文字数
・日付は「yyyy/㎜/dd」形式かどうか

**Comment by shiftdownet** [comment]
https://github.com/soudai-aisw/aisw_bihin/commit/0f38b7a1d9c036773a0776a9453779f003d64df1
で対応済
