### ISSUE TITLE
返却時に登録されている備品IDを入れても登録されていないと表示される。

### ISSUE THREAD

**Issue by shinichi-ozaki** [soudai-aisw/aisw_bihin#53]
**バグの説明**
返却時に登録されている備品IDを入れても登録されていないと表示される。

**再現手順**
1. 通常の手順で返却を実施。
2. 返却する備品のRFID読み込み状態でキーボードから
　登録されているRFID(タグID、今回は101）を入力する。
3. 登録されていない備品です。と表示され、返却処理が受理されない。

**期待動作**
登録されているRFIDであれば、返却処理を受理する。

**スクリーンショット**
なし

**再現環境:**
 - OS(Windows)
 - Python(3.8.7)
 - コミットID：e18833835adfb71647e815cf67c8c6b000d9861c

**追加情報**
原因：DBのタグIDに小数点が含まれている。　例：101.0

**Comment by shiftdownet** [comment]
101.0と入力すれば認識されます。
RFIDの書式が不明ゆえですね。。
ってきり255.255.255.255みたいにバイトコードが飛んでくるものだと。。

**Comment by shinichi-ozaki** [comment]
自分とこのRFIDは何桁かの数字の羅列だったな。
ラズパイのキットに入ってたRFID（カード、キーホルダー）の桁数は同じだったけど、
市販のRFIDシールは桁数少なかった記憶。
詳細はまた調べときます。

**Comment by shinichi-ozaki** [comment]
コミットID： dd18fee94024ff7e5e670bd99d4e7d70a16868ca で修正してあったので
本件クローズします。
